import { useState } from "react";
import Head from "next/head";

import Layout from "@/components/Layout";
import Editor from "../components/Editor";

export default function Home() {
  const [body, setBody] = useState();
  return (
    <Layout>
      <Head>
        <title>Example Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Editor</h2>
        <Editor setBody={setBody} />
        <div className="content" dangerouslySetInnerHTML={{ __html: body }} />
      </main>
    </Layout>
  );
}
