import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Editor from "../components/Editor";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [body, setBody] = useState();
  return (
    <>
      <Head>
        <title>Example Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Editor</h2>
        <Editor setBody={setBody} />
        <div className="content" dangerouslySetInnerHTML={{ __html: body }} />
      </main>
    </>
  );
}
